// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class MyData;
@class ResponseData;

@interface MyData : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name
    age:(nullable NSNumber *)age;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * age;
@end

@interface ResponseData : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name;
@property(nonatomic, copy, nullable) NSString * name;
@end

/// The codec used by MyDataApi.
NSObject<FlutterMessageCodec> *MyDataApiGetCodec(void);

@protocol MyDataApi
- (void)sendDataData:(MyData *)data completion:(void (^)(ResponseData *_Nullable, FlutterError *_Nullable))completion;
@end

extern void MyDataApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MyDataApi> *_Nullable api);

NS_ASSUME_NONNULL_END
